### PR TITLE
Update appdata file in update script

### PR DESCRIPTION
**Pull request by xduugu**

### CODE REVIEW

**Comment by Erick555** [comment]
Thx for this PR. I'm bit skeptical about auto committing changes alongside version bump as it's possible that additional actions would be needed, i.e. adding/removing patches and I prefer to avoid non buildable commits.

I also wonder if it would be possible to somewhat sanitize provided date to make sure it's in `xxxx-xx-xx` 0-9 ciphers only format to avoid typos.

**Comment by xduugu** [comment]
> Thx for this PR. I'm bit skeptical about auto committing changes alongside version bump as it's possible that additional actions would be needed, i.e. adding/removing patches and I prefer to avoid non buildable commits.

The git commit is only created locally, nothing is automatically pushed to a remote branch. I see the commit as a suggestion which needs to be checked manually, but you are not forced to used it as it. The changes in the commit are only these that are always necessary for a version bump, but, of course, you are free to modify the existing git commit (`git commit --amend`) before pushing it.

But if you see the automatic git commit as a problem, I could replace the line with a message that is printed to the terminal that can be easily copied. Something like:

You can commit the result by using the command `git commit [...]`.

> I also wonder if it would be possible to somewhat sanitize provided date to make sure it's in `xxxx-xx-xx` 0-9 ciphers only format to avoid typos. This isn't a blocker though.

Yes, it is possible. I am just not sure if it is really necessary since the commit should be anyway checked for the correct date.

**Comment by Erick555** [comment]
> But if you see the automatic git commit as a problem, I could replace the line with a message that is printed to the terminal and can be copied.

I would prefer that. Creating commit automatically (even local one) for every script usage makes me uncomfortable at least for now.

> Yes, it is possible. I am just not sure if it is really necessary since the commit should be anyway checked for the correct date.

It should be checked but it's still worth to reduce potential human errors. As I said it's not critical for this PR so it's ok if you don't have the time for doing this.

**Comment by xduugu** [comment]
I have made the following changes to the PR:
* The git command is not executed in the script anymore. Instead, a short message is printed at the end which suggests executing the command.
* The dates are now validated, but it is only a basic check. Dates likes `2020-11-31` are accepted as well, even though this date does not exist. If you want to reject these dates, too, we would have to depend on the `date` command.

**Pull request merged**
