### PR TITLE
Enable aarch64 build

### PR DESCRIPTION
**Pull request by hfiguiere**
Remove the flathub.json to enable the build.

- [x] check it builds
- [x] check it runs (Raspberry Pi 400)

### CODE REVIEW

**Comment by Erick555** [comment]
Thx for this contribution however there are at least two problems which blocks arm support:

1. I'm the only maintainer and I don't have access to arm hardware which means I can't test anything except the build on flathub thus can't help with any arm specific issues that users may hit. Because of that it's hard for me to take responsibility for supporting arm.
2. There is a plan to make this flatpak [officially maintained by upstream](https://github.com/flathub/org.mozilla.Thunderbird/issues/117). This should happen sooner or later and then there will be the same problem as for firefox flatpak - upstream doesn't produce arm binaries which would mean arm support will end and users will be left with some outdated version which is arguably poor outcome.

**Comment by barthalion** [comment]
1. I believe @hfiguiere asks because he cares about arm version availability. In the worst case you can just skip it until build failure is figured out.
2. I don't think anything is happening on that front.

**Comment by Erick555** [comment]
>     1. I believe @hfiguiere asks because he cares about arm version availability. In the worst case you can just skip it until build failure is figured out.

I was concerned about runtime failures which I wouldn't even notice if they happen.

>     2. I don't think anything is happening on that front.

AFAIK upstream intents to do it as soon as they find the time.

**Comment by hfiguiere** [comment]
If every other maintainer had the same concern, there would be barely any aarch64 packages. Also we wouldn't be able to address these concerns either since there would be no build.

As for using Mozilla official build, I will say nothing, just that not having Firefox on `aarch64` because of that is very disappointing....

**Comment by barthalion** [comment]
@Erick555 If it becomes problematic, it can be dropped, but I think it's still worth trying.

**Comment by Erick555** [comment]
@barthalion what would be the plan for aarch64 users in case it's dropped? In other repos I've seen reports from users who installed apps **years** after their arch was dropped without realizing it doesn't get any updates and is unsupported.

**Comment by hfiguiere** [comment]
Why would it get dropped?

**Comment by Erick555** [comment]
Because it may get broken in future update while nobody may found the time to fix it, because upstream takeover, etc...

**Comment by hfiguiere** [comment]
What needs to be done to get this in?

**Comment by Erick555** [comment]
Someone would need to address my concerns.

**Comment by hfiguiere** [comment]
Sorry but here I don't have have visions of the how and when it would break.  My crystal orb is broken, and the magic eight ball just say "outlook is good".

But if it does, we can advise. It's not an electron app, so I'm confident it will be fine as the core is still the same as Firefox, which build on aarch64 (android) and in general Mozilla is quite solid.

**Comment by Erick555** [comment]
Mozilla breaks with up to date rust releases (which flathub follows) like a clockwork. If this was electron app that just re-uses upstream binaries then it would much safer to add as every bug would be upstream bug then but mozilla doesn't even release for aarch64 (android is totally different platform that doesn't count). I doubt we would pass upstream testsuite if it was possible to run it.

**Comment by Erick555** [comment]
bot, build

**Comment by Erick555** [comment]
Yeah, example above although this time x86 is dead too.

**Comment by hfiguiere** [comment]
The fact that the previous build work and this one didn't is probably caused by something. 

I guess I'll mark this as WONTFIX in move on.

**Comment by Erick555** [comment]
I gave you a hint about the cause in https://github.com/flathub/org.mozilla.Thunderbird/pull/167#issuecomment-787523237 . My crystal orb work just fine.

**Comment by 1ace** [comment]
For anyone still subscribed to this PR, I've re-submitted it as https://github.com/flathub/org.mozilla.Thunderbird/pull/311 now that both reasons for rejecting it at the time (build issues and upstream support) are no longer true :)

**Pull request closed without merging**
