### PR TITLE
Remove pinentry

### PR DESCRIPTION
**Pull request by xduugu**

### CODE REVIEW

**Comment by Erick555** [comment]
How using pgp with pin protected smartcard would work without pinentry? Are smartcard with pin not supported in 78.x even with instructions from https://wiki.mozilla.org/Thunderbird:OpenPGP:Smartcards ?

**Comment by Erick555** [comment]
I asked about in on openpgp mozilla channel and they confirmed smartcards with pin are still suported and pinentry is needed to use that.

**Comment by xduugu** [comment]
I was just wondering if the flatpak pinentry is used at all as I read [somewhere else](https://github.com/flathub/org.gnu.emacs/pull/25#issuecomment-613139847) that it might not be required. So I opened this draft to be able to test external gnupg (`mail.openpgp.allow_external_gnupg` set to `true`) with a thunderbird build that does not contain a pinentry binary. However, I could only test it with a password protected gpg key, not a smartcard.

These are my results:

* Decryption works as before, I can even remove the access to `org.gnome.keyring.SystemPrompter`
* Apparently, thunderbird does not use gpg directly, but accesses gpg-agent, so that the password prompt is opened from outside of the flatpak.
* If I completely disable gpg-agent (also the systemd sockets), decryption fails.
* Turns out, decryption also fails in the thunderbird version published on flathub if gpg-agent is not running (or can be started via socket activation)

Therefore, at least in my case, gpg-agent is mandatory, and if it is mandatory, the pinentry from the flatpak is never used.

The [wiki page](https://wiki.mozilla.org/Thunderbird:OpenPGP:Smartcards#Trying_decryption) seems to support my assumption that thunderbird always uses gpg-agent (emphasis added by me):

> Try to open a message that can only be decrypted using the key from your external setup (e.g. from the smartcard of from the Qubes OS setup). **You might be prompted by gpg-agent for your key's password**, and then decryption should work, and the decrypted message contents should be shown.

It would be great if someone using a smartcard could verify my results though.

**Comment by xduugu** [comment]
> I asked about in on openpgp mozilla channel and they confirmed smartcards with pin are still suported and pinentry is needed to use that.

Did they told you it is needed inside the flatpak? I am asking, because it is of course still required, but the question is if the flatpak pinentry or the system pinentry are called. My guess is, it is always the latter. At least, as long as gpg-agent is not running inside the flatpak.

**Comment by Erick555** [comment]
> Turns out, decryption also fails in the thunderbird version published on flathub if gpg-agent is not running (or can be started via socket activation)

yes, flatpak checks if gnupg socket exist at startup and only then mounts it inside sandbox which means this socket must exist at startup time (same is is true for all sockets/services).

> Did they told you it is needed inside the flatpak? I am asking, because it is of course still required, but the question is if the flatpak pinentry or the system pinentry are called. My guess is, it is always the latter. At least, as long as gpg-agent is not running inside the flatpak.

I don't think they're familiar with flatpak so this isn't question for them. I added pinentry after [users reported](https://github.com/flathub/org.mozilla.Thunderbird/issues/4#issuecomment-557728985) they have issues without it but maybe it was some misunderstanding.

If you tested that using pin protected keys works without pinentry and `org.gnome.keyring.SystemPrompter ` then I agree to remove them (we can always revert if someone reports regression) so please add permission removal to this PR.

**Comment by xduugu** [comment]
There is one thing left that I want to test which is the enigmail migration. After that, I will complete the PR.

And at some point, we should think about dropping the access to the gpg directories by default. Thunderbird expects from smartcard users to enable an hidden preference to access the gnupg application, so I think we can also expect from them that they execute a command listed in the smartcard section of the README to adjust the flatpak overrides.

**Comment by xduugu** [comment]
Okay, I finally managed to test this PR again. The following was tested with external gnupg and works as expected:
* encryption
* decryption
* engimail migration

From my side, it is read to get merged.

**Pull request merged**
