### PR TITLE
[Thunderbird] bump to version 60

### PR DESCRIPTION
**Pull request by AdrianKoshka**
Updates Thunderbid to version 60, as per (seemingly) request in #43

### CODE REVIEW

**Comment by AdrianKoshka** [comment]
bot, build

**Comment by nedrichards** [comment]
The build system for thunderbird has changed a bit https://flathub.org/builds/#/builders/2/builds/3349

**Comment by barthalion** [comment]
This is what I changed in Arch to make it build: https://git.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/thunderbird&id=3a39cdea70e82cd26d8ffbfa7201ac75e4a62d42

**Comment by AdrianKoshka** [comment]
So `build-commands` should look like this now?
```diff
index 7841ec4..23265dc 100644
--- a/org.mozilla.Thunderbird.json
+++ b/org.mozilla.Thunderbird.json
@@ -82,8 +82,9 @@
                 }
             },
             "build-commands": [
-                "make -f client.mk",
-                "make -f client.mk install INSTALL_SDK=",
+                "./mach configure",
+                "./mach build",
+                "./mach buildsymbols",
                 "for i in 16 22 24 32 48 256;do mkdir -p /app/share/icons/hicolor/${i}x${i}/apps;cp /app/lib/thunderbird-${VERSION}/chrome/icons/default/default${i}.png /app/share/icons/hicolor/${i}x${i}/apps/thunderbird.png;done",
                 "mkdir -p /app/share/applications",
                 "cp org.mozilla.Thunderbird.desktop /app/share/applications",
```

**Comment by barthalion** [comment]
`ac_add_options --enable-application=mail` needs to be changed to `ac_add_options --enable-application=comm/mail` as well.

**Comment by AdrianKoshka** [comment]
bot, build

**Comment by AdrianKoshka** [comment]
Ah, apparently `ac_add_options --enable-gio` was dropped, will remove it and try to build again.

**Comment by AdrianKoshka** [comment]
Oh, darn it...

**Pull request merged**
