### PR TITLE
V60 fix

### PR DESCRIPTION
**Pull request by AdrianKoshka**
I made a really, really, big mistake, think I fixed it though.

### CODE REVIEW

**Comment by AdrianKoshka** [comment]
bot, build

**Comment by AdrianKoshka** [comment]
Build system is also complaining that safe browsing isn't recognized anymore? I wonder if these options were just changed...

```
 0:05.56     raise InvalidOptionError('Unknown option: %s' % without_value)
 0:05.56 mozbuild.configure.options.InvalidOptionError: Unknown option: --enable-safe-browsing
 0:05.61 *** Fix above errors and then restart with\
 0:05.62                "/usr/bin/make -f client.mk build"
```

**Comment by AdrianKoshka** [comment]
Well, ran `./configure` and didn't see anything for `gio` or `safe-browsing`.

**Comment by AdrianKoshka** [comment]
bot, build

**Comment by AdrianKoshka** [comment]
bot, build

**Comment by AdrianKoshka** [comment]
```
 0:08.25 checking for rustc... not found
 0:08.25 checking for cargo... not found
 0:08.25 ERROR: Rust compiler not found.
 0:08.25 To compile rust language sources, you must have 'rustc' in your path.
 0:08.25 See https://www.rust-lang.org/ for more information.
 0:08.25 
 0:08.25 You can install rust by running './mach bootstrap'
 0:08.25 or by directly running the installer from https://rustup.rs/
 0:08.25 
 0:08.29 *** Fix above errors and then restart with\
 0:08.29                "/usr/bin/make -f client.mk build"
 0:08.29 make: *** [client.mk:149: configure] Error 1
]2;flatpak-builder: Cleanup thunderbirdError: module thunderbird: Child process exited with code 2
FB: unmounting rofiles-fuse /srv/buildbot/worker/build-x86_64-1/org.mozilla.Thunderbird/.flatpak-builder/rofiles/rofiles-kh9Jjz
```

**Comment by AdrianKoshka** [comment]
bot, build

**Comment by AdrianKoshka** [comment]
bot, build

**Comment by AdrianKoshka** [comment]
`./mach configure` works now! :D but...now `./mach build` fails:

```
Configure complete!
Be sure to run |mach build| to pick up any changes
Running: ./mach build
FB: Running: flatpak build --die-with-parent --nofilesystem=host --filesystem=/srv/buildbot/worker/build-x86_64-5/org.mozilla.Thunderbird/.flatpak-builder/build/thunderbird-1 --bind-mount=/run/build/thunderbird=/srv/buildbot/worker/build-x86_64-5/org.mozilla.Thunderbird/.flatpak-builder/build/thunderbird-1 --build-dir=/run/build/thunderbird --bind-mount=/run/ccache=/srv/buildbot/worker/build-x86_64-5/org.mozilla.Thunderbird/.flatpak-builder/ccache --unshare=network --env=VERSION=60.0 --env=V=1 --env=CARGO_HOME=/run/build/Thunderbird/cargo --env=CCACHE_DIR=/run/ccache/disabled --env=PATH=/app/bin:/usr/bin:/usr/lib/sdk/rust-stable/bin '--env=CFLAGS=-O2 -g -fno-delete-null-pointer-checks -fno-lifetime-dse -fno-schedule-insns2' '--env=CXXFLAGS=-O2 -g -fno-delete-null-pointer-checks -fno-lifetime-dse -fno-schedule-insns2' --env=LD_LIBRARY_PATH=/app/lib --env=PKG_CONFIG_PATH=/app/lib/pkgconfig:/app/share/pkgconfig:/usr/lib/pkgconfig:/usr/share/pkgconfig --env=FLATPAK_BUILDER_N_JOBS=48 /srv/buildbot/worker/build-x86_64-5/org.mozilla.Thunderbird/.flatpak-builder/rofiles/rofiles-O9ARYR /bin/sh -c './mach build'
Error running mach:
    ['build']
The error occurred in code that was called by the mach command. This is either
a bug in the called code itself or in the way that mach is calling it.
You should consider filing a bug for this issue.
If filing a bug, please include the full output of mach, including this error
message.
The details of the failure are as follows:
error: setupterm: could not find terminal
  File "/run/build/thunderbird/python/mozbuild/mozbuild/mach_commands.py", line 172, in build
    mach_context=self._mach_context)
  File "/run/build/thunderbird/python/mozbuild/mozbuild/controller/building.py", line 944, in build
    footer = BuildProgressFooter(self.log_manager.terminal, monitor)
  File "/run/build/thunderbird/python/mozbuild/mozbuild/controller/building.py", line 576, in __init__
    Footer.__init__(self, terminal)
  File "/run/build/thunderbird/python/mozterm/mozterm/widgets.py", line 12, in __init__
    self.term = terminal or Terminal()
  File "/run/build/thunderbird/python/mozterm/mozterm/terminal.py", line 49, in Terminal
    return blessings.Terminal(**kwargs)
  File "/run/build/thunderbird/third_party/python/blessings/blessings/__init__.py", line 105, in __init__
    self._init_descriptor)
]2;flatpak-builder: Cleanup thunderbirdError: module thunderbird: Child process exited with code 1
FB: unmounting rofiles-fuse /srv/buildbot/worker/build-x86_64-5/org.mozilla.Thunderbird/.flatpak-builder/rofiles/rofiles-O9ARYR
```

**Comment by barthalion** [comment]
Possible explanation: https://bugzilla.mozilla.org/show_bug.cgi?id=1432867

**Comment by AdrianKoshka** [comment]
Huh, thanks. What do you think we should do?

**Comment by barthalion** [comment]
Try setting TERM environment variable to linux or xterm.

**Comment by AdrianKoshka** [comment]
Thanks, will do.

**Comment by AdrianKoshka** [comment]
bot, build

**Comment by AdrianKoshka** [comment]
bot, build

**Comment by AdrianKoshka** [comment]
bot, build

**Comment by AdrianKoshka** [comment]
bot, build

**Comment by AdrianKoshka** [comment]
Builds now, correctly. Going to build on my own machine + test it a bit, then hopefully release it to everyone else.

**Pull request merged**
