### PR TITLE
Update runtime and dependencies

### PR DESCRIPTION
**Pull request by xduugu**

### CODE REVIEW

**Comment by Erick555** [comment]
Thx for this PR. I prefer to stay on 19.08 runtime which is what firefox uses and using same thing may be relevant when https://github.com/flathub/org.mozilla.Thunderbird/issues/117 is solved. That also means gcr should stay as is too.

**Comment by xduugu** [comment]
@Erick555 Sure, I can revert the changes to gcr and the runtime version. There also seems to be an issue with mozilla's elf hack when using 20.08. I will update the pull request as soon as the master branch was updated to the latest thunderbird release (#143).

Regarding gcr, I do not understand why it has to stay at the current version. Is the official thunderbird build against it? I am asking, because I could not find a reference in the thunderbird source code. From my understanding, it is only a dependency of pinentry, which may not be required at all in the flatpak and could be potentially removed.

**Comment by Erick555** [comment]
See https://github.com/flathub/org.mozilla.Thunderbird/commit/404c0de969b80638b346e4a7e5891f4d0d188f0f why pinentry was added. I don't know how well it works with recent TB though so if someone proves it can't work there then it can be dropped. As for gcr version (which is used only for pinentry) I want to keep it close to other gnome tools from runtime, 19.08 has gnome components at 3.32 and mixing them with something from 3.38 may cause some issues (20.08 has gnome 3.36 iirc).

**Comment by xduugu** [comment]
Thanks for the insight. According to [this](https://github.com/flathub/org.gnu.emacs/pull/25#issuecomment-613139847), pinentry might not be required. I would like to try that in a future PR.

**Comment by Erick555** [comment]
It's possible that currently TB may not use gpg-agent even when using gpg at all is enabled in config which isn't default as they implemented opengpg support through rnp library. I don't use openpgp in TB myself so I can't verify any of this.

**Comment by xduugu** [comment]
In the default configuration, it is just as you said, gnupg is not used at all. There is, however, a configuration option to use the external gnupg for secret key operations, because rnp does not support all use cases that were possible with enigmail/gnupg ([details](https://wiki.mozilla.org/Thunderbird:OpenPGP:Smartcards)). For the enigmail migration, gnupg access is also required.

**Pull request merged**
