### PR TITLE
[wip] Add opensc

### PR DESCRIPTION
**Pull request by Erick555**
This should allow using smartcards for s/mime feature.

### CODE REVIEW

**Comment by anthr76** [comment]
Any updates on this?

**Comment by Erick555** [comment]
I refreshed this branch. The bot should build it within an hour and then you may test it. Note that flatpak support for smartcards is [very brittle](https://github.com/flatpak/flatpak/issues/4066#issuecomment-1034040834) and it may not work on your system.

**Comment by Erick555** [comment]
@anthr76 could you test?

**Comment by jmpolom** [comment]
This is necessary to get PKCS #11 tokens working in the Thunderbird flatpak. If anyone is wondering why they don't work, the absence of opensc is why. This should be tested and merged.

**Comment by Erick555** [comment]
@jmpolom are you able to test it if I refresh this branch?

**Comment by jmpolom** [comment]
> @jmpolom are you able to test it if I refresh this branch?

I do not really have a way to fully test a smart card with Thunderbird as I don't use (for example) encrypted email with it. However I installed build 42394 and added `/app/lib/opensc-pkcs11.so` as a security device via the Thunderbird settings page. It appeared to see the card and I was able to "log in" to the card with a PIN.

Can we try similar changes to the Edge and Chrome flatpaks? My understanding is the opensc-pkcs11.so lib needs to be manually added to the nss database with Chromium derivatives. Kind of annoying.

**Comment by Erick555** [comment]
You may send github PR to those flatpaks with similar changes to this one then test.

**Comment by Erick555** [comment]
Flatpak is now managed by Thunderbird team. Closing

**Pull request closed without merging**
