### PR TITLE
Update to 60.6.1 and gnome 3.32

### PR DESCRIPTION
**Pull request by Erick555**
- Update thunderbird to 60.6.1
- Update gnome runtime to 3.32
- Rewrite mozconfig
- Build only for x86_64

### CODE REVIEW

**Comment by barthalion** [comment]
Sadly, the main window exits almost immediately for me with my existing profile without printing anything interesting on the output.

**Comment by x80486** [comment]
It works for me, but I had a clean install, no previous state :sunglasses:

**Comment by Erick555** [comment]
@barthalion for me it works with existing profile, maybe try cleaning `~/.cache/thunderbird`?

**Comment by Erick555** [comment]
In general, sharing cache/config between host and flatpak apps is dangerous and in worst case may irreversibly damage profile when going back and forth between different app versions. I would opt for removing access for host cache/config from the profile. Users would need to manually copy their .thunderbird folder to `~/.var/app/org.mozilla.Thunderbird` then.

**Comment by barthalion** [comment]
Yeah, I agree with that, users should just recreate their profiles.

**Comment by Erick555** [comment]
@barthalion anything helped for your case?

**Comment by barthalion** [comment]
Yeah, brand new profile works fine. I also see `~/.cache/thunderbird:create` so I guess it should be also gone.

**Comment by Erick555** [comment]
I removed permissions mentioned above. From my POV this is ready to go.

**Pull request merged**
