### PR TITLE
Update to 102.0

### PR DESCRIPTION
**Pull request by gasinvein**
- Wasi sysroot seems required now; I didn't manage to build a complete one yet, thus wasm libraries sandbox is disabled for now.
  Fedora does the same for their Firefox build, so I'd assume it's relatively safe.
- Portal printing patch doesn't apply and doesn't seem to be needed anymore; at least, printing works fine on my machine without the patch

### CODE REVIEW

**Comment by farribeiro** [comment]
bot, build org.mozilla.Thunderbird

**Comment by Erick555** [comment]
@gasinvein could you change target branch to beta? We need some testing before deploying it for all users.

**Comment by julianfairfax** [comment]
If this is merged now does that mean I can install it just fine with the only difference being that it'll be from the beta branch?

**Comment by farribeiro** [comment]
> If this is merged now does that mean I can install it just fine with the only difference being that it'll be from the beta branch?

merge causes publishing to flathub beta channel without the later changes like llvm14 and node16

**Comment by Erick555** [comment]
Yes, you will be able to install it from flathub-beta repository. Here are [instructions](https://discourse.flathub.org/t/how-to-use-flathub-beta/2111) how to enable it for the first time.

**Comment by julianfairfax** [comment]
How long does it take for this is to be available to download? Currently it's still the previous version on the beta channel

**Comment by Erick555** [comment]
About 4 hours.

**Pull request merged**
