### PR TITLE
Update to 68.1.0

### PR DESCRIPTION
**Pull request by Erick555**

### CODE REVIEW

**Comment by ovari** [comment]
@Erick555 Thank you!

Do you need to do something else or will [Thunderbird for flatpak](https://flathub.org/apps/search/thunderbird) soon show on [Flathub](https://flathub.org/)?

Thank you once again!

**Comment by Erick555** [comment]
@ovari  For showing on Flathub I would need to ask admins to unblacklist it. For now I want to wait until people test new release.

**Comment by ovari** [comment]
@Erick555 hopes the testing and error message below helps

```
$ flatpak install --user https://dl.flathub.org/build-repo/7880/org.mozilla.Thunderbird.flatpakref
error: The application org.mozilla.Thunderbird/x86_64/test requires the runtime org.freedesktop.Platform/x86_64/19.08 which was not found
```

**Comment by Erick555** [comment]
@ovari This is now published to main flathub. If you have `org.mozilla.thunderbird` installed then `flatpak update` should get you latest version.

**Comment by ovari** [comment]
> This is now published to main flathub.

Thanks. Do you know when Thunderbird will be showing at Flathub as there are currently 0 results at https://flathub.org/apps/search/thunderbird?

**Comment by Erick555** [comment]
@ovari it's in progress: https://github.com/flathub/org.mozilla.Thunderbird/pull/74/commits/c73291cea962d08dfc9d2277513065d6ac4b1bcf

**Pull request merged**
