### PR TITLE
Use external-data-checker to check for new releases

### PR DESCRIPTION
**Pull request by xduugu**

### CODE REVIEW

**Comment by xduugu** [comment]
Apparently, I am running into https://github.com/flathub/flatpak-external-data-checker/issues/330 if the version is unchanged. :disappointed:

**Comment by xduugu** [comment]
From <https://github.com/flathub/flatpak-external-data-checker#formatting-manifests>:
> Unfortunately, it is not feasible to preserve JSON-GLib's non-standard /* */ syntax for comments. As an alternative, dictionary keys beginning with // are ignored by flatpak-builder and can be used for comments in many cases.

`finish-args` is probably not one of the *many cases* mentioned in the quote. :-(

I see two options to fix the build:
1. Remove the comments
2. Convert the manifest files to YAML, which natively supports comments

My preference would be option 2. What do you think, @Erick555 ?

**Comment by Erick555** [comment]
Removing the comments is ok.

I'm bit skeptical of general idea about using f-e-d-c though. New major TB release is around the corner and because of major releases tends to be initially unstable I plan to skip first several releases and keep following the 102.x ones for that period. That would make f-e-d-c annoying to have.

**Comment by xduugu** [comment]
f-e-d-c supports [version constraints](https://github.com/flathub/flatpak-external-data-checker#version-constraining), but unfortunately it does not work for the json checker. Other checkers like Anitya would be easier to use, but don't support the [parent source check results inheritance](https://github.com/flathub/flatpak-external-data-checker#inheriting-parent-source-check-results) that I make use of. I can, however, add an additional filter `map(select(.[0] == 102))` to the jq query to pin the major version to 102.

It is also possible to disable f-e-d-c  without removing all the `x-checker-data` configuration by [setting `"disable-external-data-checker": true` in `flathub.json`](https://github.com/flathub/flatpak-external-data-checker#on-flathub).

**Comment by xduugu** [comment]
I will close this PR as it looks like we finally get an official thunderbird flatpak in the near future. At least there is a lot of activity at the [upstream bug report](https://bugzilla.mozilla.org/show_bug.cgi?id=1290670).

**Pull request closed without merging**
